spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      -
        name: default
        url: "http://localhost:8080/v3/api-docs"